name: makmoor
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_info_plus: ^11.4.0
  esc_pos_utils_plus: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.0.9
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  horizontal_data_table: ^4.3.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  open_file_plus: ^3.4.1+1
  pdf: ^3.11.3
  permission_handler: ^12.0.0+1
  pie_chart: ^5.4.0
  print_bluetooth_thermal: ^1.0.9
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  widgets_to_image: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
